repos:
-   repo: local
    hooks:
    - id: format
      name: format
      language: system
      entry: make format
      types: [python]
    - id: test
      name: test
      language: system
      entry: make test
      types: [python]
