python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/a2c.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/ddpg.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/td3.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/sac.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/ppo.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/bc_ddpg.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/bc_sac.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/per_ddpg.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/ddpgfd.yaml --off-render --log
python run_lunarlander_continuous_v2.py --cfg-path ./configs/lunarlander_continuous_v2/sacfd.yaml --off-render --log